# Generated by Django 3.2.23 on 2025-01-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='bug_bounty_mode',
            field=models.BooleanField(default=False),
        ),
    ]
